create table authors
( ID INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name varchar(255) not null,
  birthyear integer
);

select * from authors;

INSERT INTO authors (name, birthyear) VALUES 
('George Orwell', 1903),
('Jane Austen', 1775),
('J.K. Rowling', 1965),
('Mark Twain', 1835),
('Chinua Achebe', 1930),
('Haruki Murakami', 1949),
('Toni Morrison', 1931),
('Gabriel García Márquez', 1927),
('Fyodor Dostoevsky', 1821),
('Virginia Woolf', 1882);
