create table books 
( id iNTEGER primary key generated by default as identity,
 title varchar(255) not null,
 published_year int,
 genre varchar(10),
 total_numbers_of_copy int not null,
 author_id int references authors(id) 
);
INSERT INTO books (title, published_year, genre, total_numbers_of_copy, author_id)
VALUES 
  ('To Kill a Mockingbird', 1960, 'Fiction', 10, 1),
  ('1984', 1949, 'Dystopia', 15, 2),
  ('Pride and Prejudice', 1813, 'Romance', 8, 3),
  ('The Great Gatsby', 1925, 'Fiction', 12, 4),
  ('Moby Dick', 1851, 'Adventure', 5, 5);

select * from books;
