create table loans
( id integer primary key generated by default as identity unique,
  loan_date date not null,
  return_date date,
  book_id int references books(id),
  member_id int references members(id)
);
INSERT INTO loans (loan_date, return_date, book_id, member_id)
VALUES 
    ('2025-05-01', '2025-05-10', 1, 1),
    ('2025-05-03', NULL, 2, 2),
    ('2025-04-25', '2025-05-01', 3, 3),
    ('2025-05-05', NULL, 1, 3);
select * from loans;
