create table members
( 
 id integer primary key generated by default as identity,
 name varchar(255) not null,
 email varchar(255) unique,
 join_date date not null
);
INSERT INTO members (name, email, join_date)
VALUES
  ('Alice Johnson', 'alice.johnson@example.com', '2023-01-15'),
  ('Bob Smith', 'bob.smith@example.com', '2023-02-10'),
  ('Charlie Brown', 'charlie.brown@example.com', '2023-03-05'),
  ('Diana Prince', 'diana.prince@example.com', '2023-04-20'),
  ('Ethan Hunt', 'ethan.hunt@example.com', '2023-05-25');

select * from members;
